import { useState } from "react";
import { observer } from "mobx-react-lite";
import { X, Download, FileText, Printer, Mail, Check } from "lucide-react";
import type { Trip } from "@friendinerary/types";
import toast from "react-hot-toast";
import { useStore } from "../../stores/RootStore";

interface ExportModalProps {
  trip: Trip;
  onClose: () => void;
}

const ExportModal = observer(({ trip, onClose }: ExportModalProps) => {
  const { settings } = useStore();
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleExportText = () => {
    setExporting(true);
    try {
      const lines: string[] = [
        `🗺️ ${trip.name}`,
        `📅 ${trip.startDate ? settings.formatShortDate(trip.startDate) : "TBD"} – ${trip.endDate ? settings.formatDate(trip.endDate) : "TBD"}`,
        `📍 ${trip.destinations.join(", ") || "No destinations"}`,
        "",
        "=".repeat(50),
        "",
      ];

      for (const section of trip.sections) {
        lines.push(`📌 ${section.name}${section.date ? ` (${settings.formatShortDate(section.date)})` : ""}`);
        lines.push("-".repeat(30));
        for (const [i, item] of section.placeItems.entries()) {
          lines.push(`  ${i + 1}. ${item.place.name}`);
          if (item.place.address) lines.push(`     📍 ${item.place.address}`);
          if (item.startTime) lines.push(`     🕐 ${settings.formatTime(item.startTime)}`);
          if (item.notes) lines.push(`     💬 ${item.notes}`);
        }
        lines.push("");
      }

      lines.push("=".repeat(50));
      lines.push("Generated by Friendinerary — friendinerary.com");

      const content = lines.join("\n");
      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${trip.name.replace(/[^a-z0-9]/gi, "_")}_itinerary.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setExported(true);
      toast.success("Itinerary downloaded!");
    } catch {
      toast.error("Export failed");
    } finally {
      setExporting(false);
    }
  };

  const handleCopyLink = async () => {
    const url = `${window.location.origin}/trip/${trip.id}`;
    await navigator.clipboard.writeText(url);
    toast.success("Trip link copied!");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl w-full max-w-sm">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-100 dark:border-gray-800">
          <div className="flex items-center gap-2">
            <Download className="w-5 h-5 text-brand-500" />
            <h2 className="font-semibold text-gray-900 dark:text-white">Export trip</h2>
          </div>
          <button onClick={onClose} className="p-1 text-gray-400 hover:text-gray-600 rounded-lg">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-4 space-y-2">
          <ExportOption
            icon={<FileText className="w-5 h-5" />}
            title="Export as text"
            description="Plain text file with all places and notes"
            onClick={handleExportText}
            loading={exporting}
            done={exported}
          />
          <ExportOption
            icon={<Printer className="w-5 h-5" />}
            title="Print / Save as PDF"
            description="Open print dialog to save as PDF"
            onClick={handlePrint}
          />
          <ExportOption
            icon={<Mail className="w-5 h-5" />}
            title="Copy trip link"
            description="Share a link to this trip"
            onClick={handleCopyLink}
          />
        </div>

        <div className="px-4 pb-4">
          <p className="text-xs text-center text-gray-400">
            Google Docs & calendar export coming soon
          </p>
        </div>
      </div>
    </div>
  );
});

function ExportOption({
  icon, title, description, onClick, loading, done
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
  onClick: () => void;
  loading?: boolean;
  done?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      disabled={loading}
      className="w-full flex items-center gap-3 p-3 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors text-left"
    >
      <div className="w-10 h-10 rounded-xl bg-brand-50 dark:bg-brand-900/20 flex items-center justify-center text-brand-500 flex-shrink-0">
        {done ? <Check className="w-5 h-5 text-green-500" /> : icon}
      </div>
      <div>
        <p className="text-sm font-medium text-gray-900 dark:text-white">{title}</p>
        <p className="text-xs text-gray-400">{description}</p>
      </div>
    </button>
  );
}

export default ExportModal;
